# Generated by Django 5.1.5 on 2025-01-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='No Subject', max_length=255),
        ),
    ]
