# Generated by Django 5.1.5 on 2025-01-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_message_is_sent_alter_deliverylog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipients',
            new_name='recipient',
        ),
    ]
